// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TweetServiceClient is the client API for TweetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetServiceClient interface {
	GetAllTweet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Tweets, error)
	CreateTweet(ctx context.Context, in *Tweet, opts ...grpc.CallOption) (*Empty, error)
	GetTweetById(ctx context.Context, in *TweetByIdRequest, opts ...grpc.CallOption) (*Tweets, error)
	DeleteTweetById(ctx context.Context, in *TweetByIdRequest, opts ...grpc.CallOption) (*Empty, error)
}

type tweetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetServiceClient(cc grpc.ClientConnInterface) TweetServiceClient {
	return &tweetServiceClient{cc}
}

func (c *tweetServiceClient) GetAllTweet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Tweets, error) {
	out := new(Tweets)
	err := c.cc.Invoke(ctx, "/tweet.TweetService/GetAllTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetServiceClient) CreateTweet(ctx context.Context, in *Tweet, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/tweet.TweetService/CreateTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetServiceClient) GetTweetById(ctx context.Context, in *TweetByIdRequest, opts ...grpc.CallOption) (*Tweets, error) {
	out := new(Tweets)
	err := c.cc.Invoke(ctx, "/tweet.TweetService/GetTweetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetServiceClient) DeleteTweetById(ctx context.Context, in *TweetByIdRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/tweet.TweetService/DeleteTweetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetServiceServer is the server API for TweetService service.
// All implementations should embed UnimplementedTweetServiceServer
// for forward compatibility
type TweetServiceServer interface {
	GetAllTweet(context.Context, *Empty) (*Tweets, error)
	CreateTweet(context.Context, *Tweet) (*Empty, error)
	GetTweetById(context.Context, *TweetByIdRequest) (*Tweets, error)
	DeleteTweetById(context.Context, *TweetByIdRequest) (*Empty, error)
}

// UnimplementedTweetServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTweetServiceServer struct {
}

func (UnimplementedTweetServiceServer) GetAllTweet(context.Context, *Empty) (*Tweets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTweet not implemented")
}
func (UnimplementedTweetServiceServer) CreateTweet(context.Context, *Tweet) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTweet not implemented")
}
func (UnimplementedTweetServiceServer) GetTweetById(context.Context, *TweetByIdRequest) (*Tweets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTweetById not implemented")
}
func (UnimplementedTweetServiceServer) DeleteTweetById(context.Context, *TweetByIdRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTweetById not implemented")
}

// UnsafeTweetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetServiceServer will
// result in compilation errors.
type UnsafeTweetServiceServer interface {
	mustEmbedUnimplementedTweetServiceServer()
}

func RegisterTweetServiceServer(s grpc.ServiceRegistrar, srv TweetServiceServer) {
	s.RegisterService(&TweetService_ServiceDesc, srv)
}

func _TweetService_GetAllTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).GetAllTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tweet.TweetService/GetAllTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).GetAllTweet(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TweetService_CreateTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).CreateTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tweet.TweetService/CreateTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).CreateTweet(ctx, req.(*Tweet))
	}
	return interceptor(ctx, in, info, handler)
}

func _TweetService_GetTweetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).GetTweetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tweet.TweetService/GetTweetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).GetTweetById(ctx, req.(*TweetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TweetService_DeleteTweetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).DeleteTweetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tweet.TweetService/DeleteTweetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).DeleteTweetById(ctx, req.(*TweetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TweetService_ServiceDesc is the grpc.ServiceDesc for TweetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TweetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tweet.TweetService",
	HandlerType: (*TweetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTweet",
			Handler:    _TweetService_GetAllTweet_Handler,
		},
		{
			MethodName: "CreateTweet",
			Handler:    _TweetService_CreateTweet_Handler,
		},
		{
			MethodName: "GetTweetById",
			Handler:    _TweetService_GetTweetById_Handler,
		},
		{
			MethodName: "DeleteTweetById",
			Handler:    _TweetService_DeleteTweetById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tweet.proto",
}
