// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/tweet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tweet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId  int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tweet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tweet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_proto_tweet_proto_rawDescGZIP(), []int{0}
}

func (x *Tweet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tweet) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Tweet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Tweets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweets []*Tweet `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
}

func (x *Tweets) Reset() {
	*x = Tweets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tweet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tweets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweets) ProtoMessage() {}

func (x *Tweets) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tweet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweets.ProtoReflect.Descriptor instead.
func (*Tweets) Descriptor() ([]byte, []int) {
	return file_proto_tweet_proto_rawDescGZIP(), []int{1}
}

func (x *Tweets) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

type TweetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TweetId int64 `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
}

func (x *TweetByIdRequest) Reset() {
	*x = TweetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tweet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TweetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetByIdRequest) ProtoMessage() {}

func (x *TweetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tweet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetByIdRequest.ProtoReflect.Descriptor instead.
func (*TweetByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_tweet_proto_rawDescGZIP(), []int{2}
}

func (x *TweetByIdRequest) GetTweetId() int64 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tweet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tweet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_tweet_proto_rawDescGZIP(), []int{3}
}

var File_proto_tweet_proto protoreflect.FileDescriptor

var file_proto_tweet_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x22, 0x4a, 0x0a, 0x05, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x06, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73,
	0x12, 0x24, 0x0a, 0x06, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x06,
	0x74, 0x77, 0x65, 0x65, 0x74, 0x73, 0x22, 0x2d, 0x0a, 0x10, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x77,
	0x65, 0x65, 0x74, 0x49, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xdf,
	0x01, 0x0a, 0x0c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x0c,
	0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x22, 0x00, 0x12, 0x2b, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x1a, 0x0c, 0x2e, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x74, 0x77, 0x65,
	0x65, 0x74, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x54, 0x77, 0x65, 0x65,
	0x74, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x74, 0x77, 0x65, 0x65, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tweet_proto_rawDescOnce sync.Once
	file_proto_tweet_proto_rawDescData = file_proto_tweet_proto_rawDesc
)

func file_proto_tweet_proto_rawDescGZIP() []byte {
	file_proto_tweet_proto_rawDescOnce.Do(func() {
		file_proto_tweet_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tweet_proto_rawDescData)
	})
	return file_proto_tweet_proto_rawDescData
}

var file_proto_tweet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tweet_proto_goTypes = []interface{}{
	(*Tweet)(nil),            // 0: tweet.Tweet
	(*Tweets)(nil),           // 1: tweet.Tweets
	(*TweetByIdRequest)(nil), // 2: tweet.TweetByIdRequest
	(*Empty)(nil),            // 3: tweet.Empty
}
var file_proto_tweet_proto_depIdxs = []int32{
	0, // 0: tweet.Tweets.tweets:type_name -> tweet.Tweet
	3, // 1: tweet.TweetService.GetAllTweet:input_type -> tweet.Empty
	0, // 2: tweet.TweetService.CreateTweet:input_type -> tweet.Tweet
	2, // 3: tweet.TweetService.GetTweetById:input_type -> tweet.TweetByIdRequest
	2, // 4: tweet.TweetService.DeleteTweetById:input_type -> tweet.TweetByIdRequest
	1, // 5: tweet.TweetService.GetAllTweet:output_type -> tweet.Tweets
	3, // 6: tweet.TweetService.CreateTweet:output_type -> tweet.Empty
	1, // 7: tweet.TweetService.GetTweetById:output_type -> tweet.Tweets
	3, // 8: tweet.TweetService.DeleteTweetById:output_type -> tweet.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tweet_proto_init() }
func file_proto_tweet_proto_init() {
	if File_proto_tweet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tweet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tweet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tweet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tweets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tweet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TweetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tweet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tweet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tweet_proto_goTypes,
		DependencyIndexes: file_proto_tweet_proto_depIdxs,
		MessageInfos:      file_proto_tweet_proto_msgTypes,
	}.Build()
	File_proto_tweet_proto = out.File
	file_proto_tweet_proto_rawDesc = nil
	file_proto_tweet_proto_goTypes = nil
	file_proto_tweet_proto_depIdxs = nil
}
